### ISSUE TITLE
Redirect www to the site

### ISSUE THREAD

**Issue by pauarge** [MaximeKjaer/pineapplepfl.ch#2]
If you type the URL with leading www, it doesn't show the site.

<img width="1698" alt="screen shot 2018-05-29 at 12 23 33" src="https://user-images.githubusercontent.com/7188409/40653372-3844f690-633b-11e8-99dd-7175b3f52d23.png">

**Comment by MaximeKjaer** [comment]
Fixed!

**Comment by MaximeKjaer** [comment]
Thanks for submitting the issue 😊
